rails2_studio/solutions/activerecord/config/routes.rb
Events::Application.routes.draw do
  root :to => "events#index"
  match 'upcoming-events' => 'events#index'
  
  resources :events do
    resources :registrations, :reviews
    get :search, :on => :collection
  end

  resource  :session
  resources :users

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

rails2_studio/solutions/activerecord/app/views/layouts/_flash.html.erb
<% [:notice, :warning, :error].each do |type| %>
  <% if flash[type] %>
    <div id="flash_<%= type %>" class="message">
      <p><%= flash[type] %></p>
    </div>
  <% end %>
<% end %>

rails2_studio/solutions/activerecord/app/views/layouts/_footer.html.erb
<div id="footer">
  <p>
    Copyright &copy; 2005–2010
    <a href="http://pragmaticstudio.com">The Pragmatic Studio</a>. 
    All Rights Reserved.
  </p>
  <p>
    For educational purposes only.
  </p>
</div>

rails2_studio/solutions/activerecord/app/views/layouts/_header.html.erb
<div id="header">
  <div id="logo">
    <%= link_to(image_tag("logo.jpg"), events_path) %>
  </div>
  <div id="navigation">
    <p>
      <% if logged_in? %>
        <%= link_to 'Logout', session_path, :method => :delete  %>
      <% else %>
        <%= link_to 'Join', new_user_path  %>
        <span class="separator">|</span>
        <%= link_to 'Login', new_session_path  %>
      <% end %>
    </p>
  </div>
</div>

rails2_studio/solutions/activerecord/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= @page_title || "Pragmatic Events" %></title>
  <%= stylesheet_link_tag 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= render 'layouts/flash', :flash => flash %>

  <div id="main-body">

    <div id="sidebar">
      <h1>Events</h1>
      <ul>  
        <li>
          <%= link_to raw("#{image_tag("/images/icons/date.png")} All Events"), events_path %>
        </li>
        <li>
          <%= link_to raw("#{image_tag("/images/icons/add.png")} New Event"),   new_event_path %>
        </li>
      </ul>
      
      <% unless @user_events.empty? %>
        <div id="events">
          <%= render "users/events", :events => @user_events %>
        </div>
      <% end %>
    </div> 

    <div id="content">
      <%= yield :layout %>
    </div>

  </div>

  <%= render 'layouts/footer' %>

</body>
</html>
  