rails2_studio/code/events/activerecord_labs/config/routes.rb
Events::Application.routes.draw do
  root :to => "events#index"
  match 'upcoming-events' => 'events#index'
  
  resources :events do
    resources :registrations, :reviews
    get :search, :on => :collection
  end

  resource  :session
  resources :users

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

rails2_studio/code/events/activerecord_labs/app/models/event.rb
class Event < ActiveRecord::Base
  
  has_many :registrations
  has_many :reviews
  
  has_many :attendees, 
           :source => :user, 
           :through => :registrations,
           :order => 'users.name'
  
  validates_presence_of     :name, :image_location, :starts_at, :location
  
  validates_uniqueness_of   :name
  
  validates_numericality_of :price, :greater_than_or_equal_to => 0
  
  validates_numericality_of :capacity, :only_integer => true
  
  validates_length_of       :description, :minimum => 10

  validates_format_of       :image_location, 
                            :message => "must reference a GIF, JPG, or PNG image",
                            :with => %r{\.(gif|jpg|png)$}i 
                      
  validate :price_is_a_multiple_of_five_cents
  
  def self.find_upcoming_events 
    order("starts_at").where('starts_at >= ?', Time.now)
  end
  
  # Searches for an event by name likeness.
  def self.search(name)
    self.where("name like ?", "%#{name}%")
  end
  
  # Returns all the event names which can be
  # handy for form selections, for example.
  def self.all_names
    all.map { |event| event.name }
  end
  
  def register(user)
    registration = registrations.build(:user => user)
    registration.save
  end
  
  def free?
    self.price.zero?
  end  
  
  # Returns the number of seats remaining.
  def spaces_remaining
    self.capacity - self.registrations.size
  end
  
private
  
  # ===============
  # = Validations =
  # ===============
  
  def price_is_a_multiple_of_five_cents
    unless price && (price * 100) % 5 == 0
      errors.add(:price, "must be a multiple of 5 cents")
    end
  end                      
end

rails2_studio/code/events/activerecord_labs/app/controllers/events_controller.rb
class EventsController < ApplicationController
    
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all.select do |event|
      event.starts_at >= Time.now
    end.sort_by do |event| 
      event.starts_at
    end.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.json  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else 
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url, :notice => "#{@event.name} was destroyed.") }
      format.xml  { head :ok }
    end
  end 
  
  def search
    @term = params[:term]
    @events = Event.where("name like '%#{params[:term]}%'")

    respond_to do |format|
      format.html { render :action => :index}
      format.xml  { render :xml => @events }
    end
  end
end

rails2_studio/code/events/activerecord_labs/app/helpers/events_helper.rb
module EventsHelper
  def price(event)
    event.free? ? "<strong>Free!</strong>".html_safe : number_to_currency(event.price)
  end
end

rails2_studio/code/events/activerecord_labs/app/views/events/_event.html.erb
<div class="event" id="event_<%= event.id %>">
  <h2><%= link_to event.name, event %></h2>
  <img class="event" alt="Event" src="<%= event.image_location %>"/>
  <p>
    <%= truncate(event.description, :length => 250) %>
  </p>
  <br/>
  <table class="event" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <th><%= image_tag("/images/icons/date.png") %> When?</th>
      <td><%= event.starts_at.to_s(:event_time) %></td>
    </tr>
    <tr>
      <th><%= image_tag("/images/icons/map.png") %> Where?</th>
      <td><%= event.location %></td>
    </tr>
    <tr>
      <th><%= image_tag("/images/icons/dollar.png") %> Cost?</th>
      <td><%= price(event) %></td>
    </tr>
    <tr>
      <th><%= image_tag("/images/icons/group.png") %> Capacity?</th>
      <td>
        <%= pluralize(event.capacity, 'person') %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= button_to "Register!", event_registrations_path(event) %>
      </td>
    </tr>
  </table> 
</div>                                              

rails2_studio/code/events/activerecord_labs/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<%= render :partial => "shared/errors", :locals => {:model => @event} %>

<fieldset>
  
  <div class="required-fields">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, cols: 60, rows: 7
       %>
    </div>
    <div class="field">
      <%= f.label :image_location, 'Image file' %>
      <%= f.text_field :image_location, size: 60 %>
    </div>
    <div class="field">
      <%= f.label :location %>
      <%= f.text_area :location, rows: 5 %>
    </div>
    <div class="field">
      <%= f.label :capacity %>
      <%= f.text_field :capacity %>
    </div>
    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :starts_at %>
      <%= f.datetime_select :starts_at %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %> 
  </div>  
</fieldset>

<% end %>

rails2_studio/code/events/activerecord_labs/app/views/events/edit.html.erb
<div id="banner">
 <h1>Editing Event</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

rails2_studio/code/events/activerecord_labs/app/views/events/index.html.erb
<%= render @events %>

rails2_studio/code/events/activerecord_labs/app/views/events/new.html.erb
<div id="banner">
 <h1>New Event</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

rails2_studio/code/events/activerecord_labs/app/views/events/show.html.erb
<table class="records show" cellpadding="0" cellspacing="0">
  <tr>
    <th colspan="2"><%= @event.name %></th>
  </tr>
  <tr>
    <td class="attribute">Description</td>
    <td><%= @event.description %></td>
  </tr>
  <tr>
    <td class="attribute">Image Location</td>
    <td><%= @event.image_location %></td>
  </tr>
  <tr>
    <td class="attribute">Location</td>
    <td><%= @event.location %></td>
  </tr>
  <tr>
    <td class="attribute">Capacity</td>
    <td><%= pluralize(@event.capacity, 'person') %></td>
  </tr>
  <tr>
    <td class="attribute">Price</td>
    <td><%= number_to_currency(@event.price) %></td>
  </tr>
  <tr>
    <td class="attribute">Starts</td>
    <td><%= @event.starts_at.to_s(:event_time) %></td>
  </tr>
</table>

<div class="link-menu">
  <%= link_to 'Review', new_event_review_url(@event) %> |
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Destroy', @event, 
              :confirm => 'Are you sure?', 
              :method => :delete %> |
  <%= link_to 'Back', events_path %>
</div>